livres_index:
    path:     /
    defaults: { _controller: "LivreBundle:Livres:index" }
    methods:  [GET, POST, DELETE]

livres_show:
    path:     /{id}/show
    defaults: { _controller: "LivreBundle:Livres:show" }
    methods:  GET

livres_new:
    path:     /new
    defaults: { _controller: "LivreBundle:Livres:new" }
    methods:  [GET, POST]

livres_edit:
    path:     /{id}/edit
    defaults: { _controller: "LivreBundle:Livres:edit" }
    methods:  [GET, POST]

livres_delete:
    path:     /{id}/delete
    defaults: { _controller: "LivreBundle:Livres:delete" }
    methods:  [GET, POST, DELETE]

livres_shou:
    path:     /{id}/shou
    defaults: { _controller: "LivreBundle:Livres:shou" }
    methods:  GET