event_index:
    path:     /
    defaults: { _controller: "ParticipantBundle:Event:index" }
    methods:  GET

event_show:
    path:     /{id}/show
    defaults: { _controller: "ParticipantBundle:Event:show" }
    methods:  GET



